In [65]:
import pandas as pd
import numpy as np

Q1. Pandas version

In [3]:
pd.__version__

'2.2.2'

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-09-30 22:43:37--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv’

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.02s   

2024-09-30 22:43:38 (12.7 MB/s) - ‘laptops.csv’ saved [298573/298573]



In [34]:
df = pd.read_csv('laptops.csv')
df.head(3)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   
2  ExpertBook  Intel Core i3    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0  
2        789.0

Q2. Records count

In [21]:
df.shape

(2160, 12)

Q3. Laptop brands

In [32]:
df['Brand'].nunique()

27

Q4. Missing values

In [29]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

Q5. Maximum final price

In [37]:
df[(df['Brand'] == 'Dell')]['Final Price'].max()

3936.0

Q6. Median value of Screen

In [39]:
df['Screen'].median()

15.6

In [45]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [49]:
df['Screen'].fillna(0)
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

Q7. Sum of weights

In [57]:
X = df[
    (df['Brand'] == 'Innjoo')
][['RAM', 'Storage', 'Screen']].to_numpy()

In [58]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [61]:
X_t = X.T

In [62]:
X_t

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [67]:
XTX = X_t.dot(X)

In [68]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [69]:
XTX_inv = np.linalg.inv(XTX)

In [70]:
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [71]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [73]:
w = XTX_inv.dot(X_t).dot(y)

In [75]:
w.sum().round(2)

91.3